### ISSUE TITLE
validation data preparation wrong in get_val_error_loss

### ISSUE THREAD

**Issue by yanshuaicao** [uoguelph-mlrg/theano_alexnet#6] opened 2015-04-16 06:16 UTC
When flag_para_load is False, I think the following is a bug:

Line 100 "val_img = hkl.load(str(val_filenames[val_index])" in train_funcs.py, the img_mean is not being subtracted; also because there's no "crop_and_mirror" applied as in proc_load.py, the input shape is wrong.

**Comment by gwding** [comment] 2015-04-16 20:06
Thanks for pointing out this bug! 
I personally haven't used "flag_para_load=False" for a long time.
If you already have a fix for that, could you maybe do a pull request?
Otherwise, I'll try to fix this in about 2 weeks, after finishing things I'm currently busy on.

**Comment by ScutZB** [comment] 2015-05-30 13:30
Another related problem is that para_load flag is not available on Windows platform. If you open it the following error occurs:

> LogicError: cuIpcGetMemHandle failed: OS call failed or operation not supported on this OS

It may caused by the unsupported feature in pyCuda. The function `pycuda.driver.mem_get_ipc_handle` at line 67 in file "train.py" throws this exception.
If I turn off the para_load flag the training script runs well, but the training cost doesn't decrease. It shocks around 6.9 when the iteration is more than 1000. I'm not sure what causes this. Maybe this issue?

Could you tell me how to solve this issue in detail please? Thanks.

**Comment by gwding** [comment] 2015-06-24 23:54
@yanshuaicao @ScutZB I believe the this issue is fixed by the latest pull request, closing this for now and please let us know if the problem is not solved.

**Closed as completed** 2015-06-25 01:32 UTC

**Comment by nguyenminhduc9988** [comment] 2016-03-08 11:09
The problem still persist. I have windows 8.1. CUDA 7.0 and NVIDIA 750M.
